server:
  port: 8666
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1
  server:
    #留存的服务实例低于多少比例进入保护模式
    renewal-percent-threshold: 0.5
    #是否开启保护模式
    enable-self-preservation: true
  client:
    #是否注册eureka
    register-with-eureka: true
    #是否启用获取服务注册信息
    fetch-registry: true
    service-url:
      #注册和查询都需要依赖该地址，过个以逗号分隔，
      #如果设置高可用
      #则修改配置server.port=8777，注册到http://127.0.0.1:8666/eureka/，启动作为节点1
      #修改配置server.port=8666，注册到http://127.0.0.1:8777/eureka/，启动作为节点2
      defaultZone: http://127.0.0.1:8666/eureka/