server:
  port: 8080
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/

logbook:
  write:
    level: trace
  format:
    style: http