server:
  port: 8080
management:
  server:
    port: 8023

spring:
  application:
    name: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1
      circuitBreaker:
        errorThresholdPercentage: 1
        sleepWindowInMilliseconds: 100000
  threadpool:
    default:
      coreSize: 1
      maxQueueSize: 1
      maximumSize: 1